import { readFile, copyFile, readdir, stat } from "node:fs/promises";
import { join, basename, extname, relative, sep } from "node:path";
import { config, isRemoteMode } from "../config.js";
import { getHistory } from "../comfyui/client.js";
import { ValidationError, ModelError, ComfyUIError } from "../utils/errors.js";
import { logger } from "../utils/logger.js";
import { resolveOutputDir, resolveInputDir } from "./output-dir.js";

/**
 * Resolve ComfyUI's REAL input directory (honors a custom --input-directory /
 * --base-directory). Used only for genuine local filesystem copies; HTTP uploads
 * go through the server API and don't need a path.
 */
async function getInputDir(): Promise<string> {
  return resolveInputDir();
}

/**
 * Reject filenames that would escape the ComfyUI input/ directory.
 * The MCP client is untrusted input, so `filename` must be treated as such.
 */
function assertSafeInputFilename(filename: string): string {
  // Strip any directory components — only allow a bare filename.
  const safe = basename(filename);
  if (
    !safe ||
    safe === "." ||
    safe === ".." ||
    safe !== filename ||
    safe.includes("/") ||
    safe.includes("\\") ||
    safe.includes("\0")
  ) {
    throw new ValidationError(
      `Invalid filename "${filename}": must be a bare filename with no path components.`,
    );
  }
  return safe;
}


/**
 * Copy a local image file into ComfyUI's input/ directory so it can be
 * referenced by LoadImage nodes in workflows.
 */
export async function uploadImage(
  sourcePath: string,
  filename?: string,
): Promise<{ filename: string; path: string }> {
  const inputDir = await getInputDir();
  const resolvedFilename = assertSafeInputFilename(filename ?? basename(sourcePath));

  // Validate extension
  const ext = extname(resolvedFilename).toLowerCase();
  const allowed = [".png", ".jpg", ".jpeg", ".webp", ".bmp", ".gif", ".tiff", ".tif"];
  if (!allowed.includes(ext)) {
    throw new ValidationError(
      `Unsupported image format "${ext}". Supported: ${allowed.join(", ")}`,
    );
  }

  const targetPath = join(inputDir, resolvedFilename);
  logger.info("Uploading image to ComfyUI input", { sourcePath, targetPath });

  try {
    await copyFile(sourcePath, targetPath);
  } catch (err) {
    throw new ValidationError(
      `Failed to copy image: ${err instanceof Error ? err.message : err}`,
    );
  }

  return { filename: resolvedFilename, path: targetPath };
}

/**
 * Extract embedded workflow JSON from a ComfyUI-generated PNG file.
 * ComfyUI stores workflow data in PNG tEXt chunks under the keys
 * "prompt" (API format) and "workflow" (UI format).
 */
export async function extractWorkflowFromImage(
  imagePath: string,
): Promise<{ prompt?: Record<string, unknown>; workflow?: Record<string, unknown> }> {
  const ext = extname(imagePath).toLowerCase();
  if (ext !== ".png") {
    throw new ValidationError(
      "Workflow extraction only works with PNG files. ComfyUI embeds metadata in PNG tEXt chunks.",
    );
  }

  const buffer = await readFile(imagePath);
  const result: { prompt?: Record<string, unknown>; workflow?: Record<string, unknown> } = {};

  // Parse PNG chunks to find tEXt/iTXt chunks with "prompt" or "workflow" keys
  const chunks = parsePngTextChunks(buffer);

  for (const { keyword, text } of chunks) {
    if (keyword === "prompt") {
      try {
        result.prompt = JSON.parse(text);
      } catch {
        logger.warn("Failed to parse 'prompt' PNG metadata as JSON");
      }
    } else if (keyword === "workflow") {
      try {
        result.workflow = JSON.parse(text);
      } catch {
        logger.warn("Failed to parse 'workflow' PNG metadata as JSON");
      }
    }
  }

  if (!result.prompt && !result.workflow) {
    throw new ValidationError(
      "No ComfyUI workflow metadata found in this PNG. The image may not have been generated by ComfyUI, or metadata embedding may have been disabled.",
    );
  }

  return result;
}

interface PngTextChunk {
  keyword: string;
  text: string;
}

/**
 * Low-level PNG tEXt/iTXt chunk parser.
 * PNG format: 8-byte signature, then chunks of [4-byte length][4-byte type][data][4-byte CRC].
 */
function parsePngTextChunks(buffer: Buffer): PngTextChunk[] {
  const results: PngTextChunk[] = [];

  // Verify PNG signature
  const PNG_SIG = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  if (buffer.length < 8 || !buffer.subarray(0, 8).equals(PNG_SIG)) {
    throw new ValidationError("Not a valid PNG file");
  }

  let offset = 8; // Skip signature

  while (offset + 8 <= buffer.length) {
    const chunkLength = buffer.readUInt32BE(offset);
    const chunkType = buffer.subarray(offset + 4, offset + 8).toString("ascii");
    const dataStart = offset + 8;
    const dataEnd = dataStart + chunkLength;

    if (dataEnd > buffer.length) break;

    if (chunkType === "tEXt") {
      // tEXt: keyword\0text
      const data = buffer.subarray(dataStart, dataEnd);
      const nullIdx = data.indexOf(0);
      if (nullIdx >= 0) {
        const keyword = data.subarray(0, nullIdx).toString("latin1");
        const text = data.subarray(nullIdx + 1).toString("latin1");
        results.push({ keyword, text });
      }
    } else if (chunkType === "iTXt") {
      // iTXt: keyword\0compressionFlag\0compressionMethod\0languageTag\0translatedKeyword\0text
      const data = buffer.subarray(dataStart, dataEnd);
      const nullIdx = data.indexOf(0);
      if (nullIdx >= 0) {
        const keyword = data.subarray(0, nullIdx).toString("utf-8");
        const compressionFlag = data[nullIdx + 1];
        // Skip compression method (1 byte), language tag, translated keyword
        let textStart = nullIdx + 3; // past null, compressionFlag, compressionMethod
        // Skip language tag (null-terminated)
        const langEnd = data.indexOf(0, textStart);
        if (langEnd >= 0) {
          textStart = langEnd + 1;
          // Skip translated keyword (null-terminated)
          const transEnd = data.indexOf(0, textStart);
          if (transEnd >= 0) {
            textStart = transEnd + 1;
          }
        }
        const textData = data.subarray(textStart);
        if (compressionFlag === 0) {
          results.push({ keyword, text: textData.toString("utf-8") });
        }
        // We skip compressed iTXt chunks — ComfyUI typically uses uncompressed
      }
    }

    if (chunkType === "IEND") break;

    // Next chunk: length(4) + type(4) + data(chunkLength) + CRC(4)
    offset = dataEnd + 4;
  }

  return results;
}

export interface OutputImage {
  filename: string;
  path: string;
  size: number;
  modified: string;
  /** Subfolder relative to the output dir ("" for top level), forward-slash
   *  normalized. ComfyUI writes to subfolders when a node's filename_prefix
   *  contains a path (e.g. SaveVideo "video/clip" → output/video/clip_00001.mp4).
   *  Pass { filename, subfolder } to get_image (action:"get") / upload_image (action:"stage"). */
  subfolder: string;
  /** Media kind derived from the file extension. */
  kind: "image" | "video";
}

// Still-image extensions.
const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".bmp"]);
// Video / animation extensions written by VHS_VideoCombine, LTX, WAN, etc.
// NOTE: .webp and .gif can be still OR animated; ComfyUI's video nodes emit
// them as animations, so they're classified as "video" here.
const VIDEO_EXTS = new Set([".mp4", ".webm", ".mov", ".mkv", ".m4v", ".avi", ".gif", ".webp"]);
// Everything we list (images + videos/animations).
const MEDIA_EXTS = new Set([...IMAGE_EXTS, ...VIDEO_EXTS]);

function mediaKind(ext: string): "image" | "video" {
  return VIDEO_EXTS.has(ext) ? "video" : "image";
}

/**
 * List image AND video/animation files in the ComfyUI output directory.
 *
 * Covers VHS_VideoCombine / LTX / WAN video outputs (.mp4, .webm, …) in addition
 * to still images, because ComfyUI's /history often does NOT register VHS-style
 * video outputs — so a filesystem scan is the reliable way to confirm a finished
 * video render.
 */
/** Where a listing came from, and what established it. */
export interface OutputListingSource {
  /** The directory that was actually scanned. Absent on the /history path,
   *  which has no directory to name — it is a listing from the server's
   *  in-memory history, not from disk. */
  directory?: string;
  /** How the answer was produced, so a caller never has to guess which. */
  basis: "local-scan" | "server-history";
}

/**
 * The listing PLUS where it came from.
 *
 * `listOutputImages` returns bare filenames, which forces any caller that needs
 * the path to reconstruct it — and the obvious reconstruction (the workspace
 * path from `install_comfyui (action:"environment")`) is WRONG on every install launched with
 * `--output-directory`, in the silent way: the filenames look plausible against
 * it, so a caller that does not stat them reports a directory holding nothing
 * (#899, observed live).
 *
 * The directory is resolved exactly ONCE, here, and travels with the entries it
 * describes. Resolving it a second time in the caller would be the same class of
 * bug this fixes: two answers to one question, free to disagree.
 */
export async function listOutputMedia(options?: {
  limit?: number;
  pattern?: string;
}): Promise<{ images: OutputImage[]; source: OutputListingSource }> {
  const limit = options?.limit ?? 20;
  const pattern = options?.pattern?.toLowerCase();

  // REMOTE mode: no local filesystem to scan. Derive the output media from
  // ComfyUI's /history (HTTP, works against a remote instance) instead. Size and
  // modification time are unavailable over HTTP, so they come back as 0 / "".
  // Keyed off isRemoteMode() ALONE (#877): when a remote target coexists with an
  // unrelated local COMFYUI_PATH, scanning the local output dir would report the
  // wrong machine's outputs — but the converse test, `!config.comfyuiPath`, was
  // never a test for "no local path". It reads one ENV VAR, while a local
  // portable install is perfectly well located by the SAVED DEFAULT WORKSPACE,
  // which `resolveOutputDir` consults and `install_comfyui (action:"environment")` reports. So a local
  // install with `COMFYUI_PATH` unset silently took the remote branch, asked
  // /history — which had been emptied by a restart — and returned `[]` over an
  // output directory holding the files the caller was asking about. A silent
  // wrong answer, not an error: the agent concludes the file does not exist.
  if (isRemoteMode()) {
    return {
      images: await listOutputImagesFromHistory(limit, pattern),
      source: { basis: "server-history" },
    };
  }

  // Local. `resolveOutputDir` already knows every way this path can be
  // established, so let it answer rather than pre-judging on one env var.
  let outputDir: string;
  try {
    outputDir = await resolveOutputDir();
  } catch (err) {
    // The local root could not be established. /history is the only source left,
    // and it CANNOT see the disk — so a zero result from it does not establish
    // that there are no outputs. Falling back is right; reporting its emptiness
    // as an answer is not.
    const fromHistory = await listOutputImagesFromHistory(limit, pattern);
    if (fromHistory.length > 0) {
      return { images: fromHistory, source: { basis: "server-history" } };
    }
    throw new ComfyUIError(
      `Could not determine this ComfyUI's output directory (${err instanceof Error ? err.message : String(err)}), ` +
        `so the local output folder was never scanned. ComfyUI's /history was asked instead and ` +
        `returned nothing — but history is emptied by a restart and cannot see files on disk, so ` +
        `that is NOT a finding that there are no outputs. Set COMFYUI_PATH, or save a default ` +
        `workspace (workspace tool, action 'set_default'), so the output folder can be read directly.`,
      "OUTPUT_DIR_UNKNOWN",
    );
  }

  // RECURSIVE scan: ComfyUI writes to subfolders when a node's filename_prefix
  // contains a path (SaveVideo / VHS / "video/clip" → output/video/clip_00001.mp4).
  // A flat readdir of the top level silently misses those — so a finished video can
  // look "not found" even though the dir resolved correctly. Walk the whole tree.
  let dirents;
  try {
    dirents = await readdir(outputDir, { recursive: true, withFileTypes: true });
  } catch (err) {
    // We know WHERE the outputs are and could not read them. That is not an
    // empty directory, and returning `[]` told the caller their file does not
    // exist when the truth is we could not look (#877).
    throw new ComfyUIError(
      `Could not read the ComfyUI output directory "${outputDir}": ` +
        `${err instanceof Error ? err.message : String(err)}. This is NOT a finding that there ` +
        `are no outputs — the directory could not be listed at all.`,
      "OUTPUT_DIR_UNREADABLE",
    );
  }

  const images: OutputImage[] = [];
  // How many entries MATCHED the query, versus how many we could actually stat.
  // A per-file stat failure is skipped silently, which is fine when it is one
  // file among many — but if it swallows every match, the caller gets `[]` over
  // a directory that demonstrably held what they asked for (codex gate).
  let matched = 0;

  for (const dirent of dirents) {
    if (!dirent.isFile()) continue;
    const ext = extname(dirent.name).toLowerCase();
    if (!MEDIA_EXTS.has(ext)) continue;

    // Dirent.parentPath (Node ≥20.12) is the absolute dir holding the entry.
    const parent = dirent.parentPath ?? outputDir;
    const subfolder = relative(outputDir, parent).split(sep).join("/"); // "" at top level
    const relPath = subfolder ? `${subfolder}/${dirent.name}` : dirent.name;
    // Match the pattern against the subfolder-relative path so "video/clip" works.
    if (pattern && !relPath.toLowerCase().includes(pattern)) continue;

    const filePath = join(parent, dirent.name);
    matched += 1;
    try {
      const info = await stat(filePath);
      images.push({
        filename: dirent.name,
        path: filePath,
        size: info.size,
        modified: info.mtime.toISOString(),
        subfolder,
        kind: mediaKind(ext),
      });
    } catch {
      // One file that vanished between readdir and stat, or that we cannot read,
      // is not worth failing the whole listing over — skip it. But see the check
      // below: skipping EVERY match is a different statement entirely.
      continue;
    }
  }

  if (matched > 0 && images.length === 0) {
    // Every entry that matched the query failed to stat. Returning `[]` here says
    // "there are none" over a directory that demonstrably held what was asked for
    // — the same fold as the two above, at the last place it can still happen
    // (codex gate).
    throw new ComfyUIError(
      `Found ${matched} matching file(s) under "${outputDir}", but none of them could be read ` +
        `(every stat failed — a permissions or I/O problem, or they were all removed mid-scan). ` +
        `This is NOT a finding that there are no outputs.`,
      "OUTPUT_ENTRIES_UNREADABLE",
    );
  }

  // Sort newest first
  images.sort((a, b) => b.modified.localeCompare(a.modified));

  return {
    images: images.slice(0, limit),
    source: { directory: outputDir, basis: "local-scan" },
  };
}

/**
 * Just the entries. Kept because most callers only want the list; anything that
 * needs to SAY where the files are must use `listOutputMedia`, so the path it
 * reports is the path that was scanned.
 */
export async function listOutputImages(options?: {
  limit?: number;
  pattern?: string;
}): Promise<OutputImage[]> {
  return (await listOutputMedia(options)).images;
}

/**
 * Remote-mode source for listOutputImages: derive output media from ComfyUI's
 * /history (HTTP) when there is no local filesystem to scan. Walks every history
 * entry's node outputs (images + videos/gifs), keeps only those that landed in
 * the "output" directory, dedupes by subfolder/filename, and returns them
 * newest-first (history is roughly insertion-ordered, so we iterate in reverse).
 * Size/modified are unavailable over HTTP and come back as 0 / "".
 */
async function listOutputImagesFromHistory(
  limit: number,
  pattern?: string,
): Promise<OutputImage[]> {
  let history: Record<string, { outputs?: Record<string, unknown> }>;
  try {
    history = await getHistory();
  } catch (err) {
    // A FAILED request is not an empty history (codex gate). Returning `[]` here
    // told the caller there are no outputs when we never got an answer at all —
    // and in remote mode this is the only source, so that `[]` was the whole
    // reply. Throwing makes the difference visible; the caller upstream already
    // distinguishes "history had nothing" from "history could not be asked".
    throw new ComfyUIError(
      `Could not read ComfyUI's generation history (${err instanceof Error ? err.message : String(err)}). ` +
        `This is NOT a finding that there are no outputs — the history could not be read at all.`,
      "HISTORY_UNREADABLE",
    );
  }

  const seen = new Set<string>();
  const images: OutputImage[] = [];
  const entries = Object.values(history);

  // Newest-first: history is keyed in roughly chronological (insertion) order,
  // so iterate from the end.
  for (let i = entries.length - 1; i >= 0; i--) {
    const outputs = entries[i]?.outputs;
    if (!outputs || typeof outputs !== "object") continue;

    for (const nodeOutput of Object.values(outputs)) {
      if (!nodeOutput || typeof nodeOutput !== "object") continue;
      const out = nodeOutput as Record<string, unknown>;
      // SaveImage emits under 'images'; SaveVideo/VHS/CreateVideo under
      // 'videos' | 'video' | 'gifs'. mediaKind() then classifies by extension.
      for (const key of ["images", "videos", "video", "gifs"] as const) {
        const arr = out[key];
        if (!Array.isArray(arr)) continue;
        for (const m of arr) {
          if (!m || typeof m !== "object") continue;
          const media = m as {
            filename?: unknown;
            subfolder?: unknown;
            type?: unknown;
          };
          if (typeof media.filename !== "string" || media.filename.length === 0) {
            continue;
          }
          // Only list assets in the output directory (skip temp previews).
          const type = typeof media.type === "string" ? media.type : "output";
          if (type !== "output") continue;
          const ext = extname(media.filename).toLowerCase();
          if (!MEDIA_EXTS.has(ext)) continue;
          const subfolder =
            typeof media.subfolder === "string" ? media.subfolder : "";
          const relPath = subfolder
            ? `${subfolder}/${media.filename}`
            : media.filename;
          if (pattern && !relPath.toLowerCase().includes(pattern)) continue;
          const dedupeKey = relPath.toLowerCase();
          if (seen.has(dedupeKey)) continue;
          seen.add(dedupeKey);
          images.push({
            filename: media.filename,
            // ComfyUI-relative reference; the absolute path is unknown over HTTP.
            path: relPath,
            size: 0,
            modified: "",
            subfolder,
            kind: mediaKind(ext),
          });
        }
      }
    }

    if (images.length >= limit) break;
  }

  return images.slice(0, limit);
}

import { fetchImage, uploadImageHttp } from "../comfyui/client.js";
import { readFile as nodeReadFile } from "node:fs/promises";

/**
 * Reject filename / subfolder values that could traverse out of ComfyUI's
 * output, input or temp directory when forwarded to the /view endpoint.
 *
 * ComfyUI's /view handler joins the requested `subfolder` and `filename`
 * onto the configured base directory; the server has historically been
 * permissive about ".." segments and absolute paths in those parameters
 * (see e.g. comfyanonymous/ComfyUI#785), so an attacker who can reach the
 * MCP tool surface could otherwise pivot through get_image (action:"get"/"view") /
 * upload_image (action:"stage") to read arbitrary files from the ComfyUI host.
 *
 * Legitimate ComfyUI values are a single filename (no separators) and a
 * relative subfolder produced by listOutputImages (forward-slash joined,
 * no ".." segments). Anything outside that shape is refused here BEFORE
 * the request is forwarded.
 */
function assertSafeViewRef(filename: string, subfolder: string): void {
  if (typeof filename !== "string" || filename.length === 0) {
    throw new ValidationError("filename is required");
  }
  if (filename.includes("\0") || (subfolder && subfolder.includes("\0"))) {
    throw new ValidationError(
      "filename / subfolder must not contain NUL bytes",
    );
  }
  // Filename must be a single path segment — no separators, no traversal.
  if (
    filename.includes("/") ||
    filename.includes("\\") ||
    filename === "." ||
    filename === ".." ||
    filename.split(/[\\/]/).some((s) => s === "..")
  ) {
    throw new ValidationError(
      `Invalid filename "${filename}": must be a single filename without path separators or '..' segments`,
    );
  }
  if (!subfolder) return;
  // Subfolder must be a forward-slash-joined relative path with no ".."
  // segments and no Windows-style drive / absolute prefix.
  if (
    subfolder.startsWith("/") ||
    subfolder.startsWith("\\") ||
    /^[A-Za-z]:[\\/]/.test(subfolder)
  ) {
    throw new ValidationError(
      `Invalid subfolder "${subfolder}": must be relative to the ComfyUI media directory`,
    );
  }
  const segments = subfolder.split(/[\\/]/);
  if (segments.some((s) => s === "..")) {
    throw new ValidationError(
      `Invalid subfolder "${subfolder}": '..' segments are not allowed`,
    );
  }
}

/**
 * Media formats get_image can save, identified by magic-byte sniff (#663).
 * Format — not just family — so a cross-format mislabel (MP3 bytes declared
 * audio/wav) is rejected even when both byte streams are genuine media.
 */
type MediaFormat =
  | "mp4-video"
  | "mp4-audio"
  | "ebml"
  | "avi"
  | "wav"
  | "flac"
  | "ogg"
  | "mpegaudio"
  | "aac";

// EBML magic and MPEG/ADTS frame syncs are only 2–4 bytes — short enough for
// a truncated error-prefix to satisfy them — so formats with no cheap local
// structure to validate require a plausible minimum file size instead.
const MIN_MEDIA_BYTES = 256;

/**
 * Magic-byte sniff for the video/audio formats get_image can save (#663).
 * Returns the media FORMAT the payload proves itself to be, or null when it
 * matches none of them. Each check validates STRUCTURE, not just a leading
 * signature: MP4/MOV/M4V/M4A need a well-formed "ftyp" box, RIFF containers
 * (WAV/AVI) a chunk size consistent with the delivered body, FLAC the
 * mandatory STREAMINFO first block, Ogg a version-0 page header whose
 * segment table fits inside the body, and ID3 a syncsafe tag size that fits.
 * A textual junk body (JSON/HTML error page) or a truncated prefix matches
 * none of these.
 */
function sniffMediaFormat(base64: string): MediaFormat | null {
  // 40 base64 chars decode to the first 30 bytes — enough for the deepest
  // header below (the 27-byte Ogg page header).
  const head = Buffer.from(base64.slice(0, 40), "base64");
  const bodyLength =
    Math.floor((base64.length * 3) / 4) -
    (base64.endsWith("==") ? 2 : base64.endsWith("=") ? 1 : 0);
  const ascii = (start: number, end: number) =>
    head.subarray(start, end).toString("ascii");
  if (head.length >= 16 && ascii(4, 8) === "ftyp") {
    // mp4/mov/m4v/m4a — require a well-formed ftyp BOX, not just the four
    // bytes "ftyp": the box size (big-endian uint32) must cover the header +
    // major brand + minor version (>= 16) and not exceed the actual body
    // length, and the major brand must be printable ASCII. An 8-byte
    // truncated body ending in "ftyp" fails every one of these.
    const boxSize = head.readUInt32BE(0);
    const printableBrand = head
      .subarray(8, 12)
      .every((b) => b >= 0x20 && b <= 0x7e);
    if (boxSize >= 16 && boxSize <= bodyLength && printableBrand) {
      // M4A/M4B are audio-only brands (m4a audio in an mp4 container); the
      // rest (isom/mp41/mp42/avc1/qt/M4V…) are video.
      const brand = ascii(8, 12);
      return brand === "M4A " || brand === "M4B " ? "mp4-audio" : "mp4-video";
    }
  }
  if (head.length >= 4 && head.readUInt32BE(0) === 0x1a45dfa3) {
    // webm/mkv — EBML magic is only 4 bytes; require a plausible file size.
    if (bodyLength >= MIN_MEDIA_BYTES) return "ebml";
  }
  if (head.length >= 8 && ascii(0, 4) === "fLaC") {
    // flac — the magic must be followed by the mandatory first metadata
    // block: a STREAMINFO block header (type 0, length exactly 34).
    if (
      (head[4] & 0x7f) === 0 &&
      head.readUIntBE(5, 3) === 34 &&
      bodyLength >= 42
    ) {
      return "flac";
    }
  }
  if (head.length >= 27 && ascii(0, 4) === "OggS") {
    // ogg — the page version byte must be 0 and the segment table must fit
    // inside the body (27-byte page header + page_segments bytes).
    if (head[4] === 0 && 27 + head[26] <= bodyLength) return "ogg";
  }
  if (head.length >= 12 && ascii(0, 4) === "RIFF") {
    // wav/avi — the RIFF chunk size (file size − 8) must be consistent with
    // the body actually delivered: at least the 4-byte form type, and never
    // claiming more bytes than we have (a truncated/fabricated prefix).
    const riffSize = head.readUInt32LE(4);
    if (riffSize >= 4 && riffSize + 8 <= bodyLength) {
      const form = ascii(8, 12);
      if (form === "WAVE") return "wav";
      if (form === "AVI ") return "avi";
    }
  }
  if (head.length >= 10 && ascii(0, 3) === "ID3") {
    // mp3 with an ID3v2 tag — the 4 tag-size bytes must be syncsafe (7-bit)
    // and the declared tag must fit inside the body; a bare "ID3" prefix
    // fails both, and the floor rejects a tag with no audio behind it.
    if (head.subarray(6, 10).every((b) => (b & 0x80) === 0)) {
      const tagSize =
        (head[6] << 21) | (head[7] << 14) | (head[8] << 7) | head[9];
      if (tagSize + 10 <= bodyLength && bodyLength >= MIN_MEDIA_BYTES) {
        return "mpegaudio";
      }
    }
  }
  if (head.length >= 2 && head[0] === 0xff && (head[1] & 0xe0) === 0xe0) {
    // mp3 / aac frame sync — 2 bytes is an error-prefix-sized signature, so
    // require a plausible file size. ADTS (aac) frames always have the MPEG
    // layer bits 00; mp3/mp2 frames have them set.
    if (bodyLength >= MIN_MEDIA_BYTES) {
      return (head[1] & 0x06) === 0 ? "aac" : "mpegaudio";
    }
  }
  return null;
}

/**
 * Declared content-type → the media format its payload must sniff as (#663).
 * Cross-format mislabels within a family (MP3 bytes labeled audio/wav) are
 * rejected just like cross-family ones. Unlisted media types fail closed;
 * application/octet-stream is handled separately and accepts any format.
 */
const MEDIA_FORMAT_BY_MIME: Record<string, MediaFormat> = {
  "video/mp4": "mp4-video",
  "video/quicktime": "mp4-video",
  "video/x-m4v": "mp4-video",
  "video/webm": "ebml",
  "video/x-matroska": "ebml",
  "video/x-msvideo": "avi",
  "video/avi": "avi",
  "video/msvideo": "avi",
  "audio/wav": "wav",
  "audio/x-wav": "wav",
  "audio/wave": "wav",
  "audio/vnd.wave": "wav",
  "audio/mpeg": "mpegaudio",
  "audio/mp3": "mpegaudio",
  "audio/aac": "aac",
  "audio/x-aac": "aac",
  "audio/flac": "flac",
  "audio/x-flac": "flac",
  "audio/ogg": "ogg",
  "audio/mp4": "mp4-audio",
  "audio/x-m4a": "mp4-audio",
};

/**
 * Filename extension → the media format its payload must sniff as (#663).
 * application/octet-stream declares nothing, so the requested FILENAME is the
 * only remaining claim: a WAV body returned as "clip.mp4" would otherwise be
 * saved under a video extension it isn't. Unlisted extensions declare nothing
 * we can check and pass any valid media format (fail-open for exotic-but-real
 * assets — the bytes still have to prove themselves via the structural sniff).
 */
const MEDIA_FORMAT_BY_EXTENSION: Record<string, MediaFormat> = {
  ".mp4": "mp4-video",
  ".mov": "mp4-video",
  ".m4v": "mp4-video",
  ".m4a": "mp4-audio",
  ".m4b": "mp4-audio",
  ".webm": "ebml",
  ".mkv": "ebml",
  ".avi": "avi",
  ".wav": "wav",
  ".mp3": "mpegaudio",
  ".aac": "aac",
  ".flac": "flac",
  ".ogg": "ogg",
  ".oga": "ogg",
};

/** Image extensions claim a still image — never consistent with a sniffed
 *  video/audio payload (an MP4 saved as clip.png is the same corruption). */
const IMAGE_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".webp",
  ".gif",
  ".bmp",
  ".tif",
  ".tiff",
  ".avif",
]);

/**
 * Fetch a generated image from ComfyUI via HTTP /view endpoint.
 * Does NOT require COMFYUI_PATH — works with remote ComfyUI instances.
 *
 * By default only image/* payloads are accepted. Pass `allowMedia: true` to
 * also accept video/* and audio/* (e.g. a VHS_VideoCombine .mp4) so the caller
 * can save them to disk — /view returns raw bytes for any media type. Media
 * acceptance sniffs the payload's magic bytes instead of trusting the declared
 * content-type, so a JSON/HTML error body mislabeled as video/mp4 is still
 * rejected — and genuine media a proxy serves as application/octet-stream
 * (ComfyUI itself reports video/mp4 via mimetypes) still passes. The sniffed
 * media format must also match the declared subtype (MP3 bytes labeled
 * audio/wav are rejected).
 */
export async function getOutputImage(
  filename: string,
  type: "output" | "input" | "temp" = "output",
  subfolder = "",
  {
    allowMedia = false,
    /**
     * Accept a `.json` attachment whose bytes actually PARSE as JSON (#1373).
     *
     * A ComfyUI input directory legitimately holds workflow `.json` files, and `get_image`
     * refused to save them: the reporter's server labelled one `video/json`, which is
     * neither `image/*` nor a sniffable media format.
     *
     * NOT AN ADDITION TO THE ACCEPT LIST. I could not reproduce that header — a stock
     * ComfyUI 0.31.1 here returns `application/json` for the same request, so `video/json`
     * comes from something in their stack, and the next install will invent a different
     * one. Accepting the specific string would fix one machine.
     *
     * The declared type is a claim about the payload; parsing is a fact about it. So this
     * follows the rule the media branch above already applies — bytes must be what they
     * are said to be — and simply asks the question JSON can answer directly.
     */
    allowJson = false,
  }: { allowMedia?: boolean; allowJson?: boolean } = {},
): Promise<{ base64: string; mimeType: string; filename: string }> {
  assertSafeViewRef(filename, subfolder);
  const result = await fetchImage(filename, type, subfolder);

  // Guard against non-image /view payloads. ComfyUI (or a reverse proxy in
  // front of it) can answer /view with a 200 whose body is actually a JSON or
  // HTML error page, or an empty body — this happens most often for `type=input`
  // refs, where the caller picked a filename/subfolder that doesn't resolve to a
  // real input file. The old code saved those bytes verbatim as a `.png` and
  // returned them as an inline image block, so the MCP client then choked trying
  // to decode them ("Unexpected end of JSON input"). Fail loudly and structured
  // instead, so get_image surfaces a clean not-found rather than a corrupt image.
  //
  // Under allowMedia the same junk body can arrive labeled video/mp4 — the
  // declared content-type alone is no proof, and get_image would save the junk
  // bytes as a working .mp4. So media payloads must also SNIFF as media, and
  // the sniffed FORMAT must match the declared subtype exactly: MP3 bytes
  // labeled audio/wav are rejected even though both are audio, otherwise the
  // asset is saved under a corrupt extension. The generic
  // application/octet-stream label declares no format, so any genuine media
  // signature passes.
  const mime = result.mimeType.toLowerCase();
  const isImage = mime.startsWith("image/");
  const sniffedFormat = allowMedia ? sniffMediaFormat(result.base64) : null;
  const ext = extname(filename).toLowerCase();
  // The sniffed format must satisfy EVERY claim present: the declared
  // content-type (exact subtype match), and the requested filename's
  // extension whenever we can classify it — audio/wav bytes requested as
  // clip.mp4 pass mime↔sniff yet would still land on disk as a corrupt .mp4.
  const extOk =
    !IMAGE_EXTENSIONS.has(ext) &&
    (!MEDIA_FORMAT_BY_EXTENSION[ext] || MEDIA_FORMAT_BY_EXTENSION[ext] === sniffedFormat);
  const isMedia =
    sniffedFormat !== null &&
    extOk &&
    (mime === "application/octet-stream" ||
      MEDIA_FORMAT_BY_MIME[mime] === sniffedFormat);
  // A `.json` request whose bytes parse as JSON is accepted whatever the server called
  // them (#1373). Gated on the REQUESTED extension so this can never widen the image or
  // media paths, and on a successful parse so the rejection this function exists for is
  // untouched: an HTML error page, a login redirect or a truncated body does not parse and
  // is still refused. ComfyUI answers 200 with an error body often enough that this check
  // is the only thing standing between the caller and a corrupt "image".
  const jsonRefusal = allowJson && ext === ".json" ? jsonAttachmentRefusal(result.base64) : null;
  const isJson = allowJson && ext === ".json" && jsonRefusal === null;
  // WHICH REFUSAL THIS IS decides the code, the message and the remedy — see
  // `jsonAttachmentRefusal`. Byte length was the first attempt at this discriminator and it
  // got the error-envelope case backwards: a `/view` that answers `{"error":"not found"}`
  // is the server reporting an ABSENT FILE, and calling that a content refusal sends the
  // caller to inspect a payload when the filename is the thing to look at.
  const contentRejected = jsonRefusal?.kind === "content";

  if ((!isImage && !isMedia && !isJson) || result.base64.length === 0) {
    const where = subfolder ? `${type}/${subfolder}` : type;
    throw new ComfyUIError(
      contentRejected
        ? // NAME THE ACTUAL REASON (#1373). "The file may not exist" for a body that
          // arrived and was rejected on its CONTENT sends the caller to re-check a
          // filename that is perfectly correct — the wrong-cause failure this issue is
          // about, reproduced by its own fix.
          `ComfyUI /view returned ${jsonRefusal?.reason}, for "${filename}" (${where}). ` +
          `Nothing was saved.`
        : jsonRefusal
          ? // A MISSING-kind JSON refusal: say what came back AND point at the name, which
            // is the part the caller can act on.
            `ComfyUI /view returned ${jsonRefusal.reason}, for "${filename}" (${where}). ` +
            `Nothing was saved. The file may not exist in the ComfyUI ${type} directory — ` +
            `check the filename/subfolder (e.g. via get_image (action:"list_outputs") or get_history).`
          : `ComfyUI /view did not return an image for "${filename}" (${where}); ` +
          `got ${result.base64.length === 0 ? "an empty response" : `content-type "${result.mimeType}"`}. ` +
          `The file may not exist in the ComfyUI ${type} directory — ` +
          `check the filename/subfolder (e.g. via get_image (action:"list_outputs") or get_history).`,
      // THE CODE HAS TO AGREE WITH THE MESSAGE (codex P2). The message names the real
      // reason, but a caller that branches on the code — which is the whole point of
      // having one — still read IMAGE_NOT_FOUND and went off to re-check a filename that
      // was never wrong. That is the same wrong-cause failure as the prose, one layer
      // down, and it is the layer that automation reads.
      contentRejected ? "ATTACHMENT_CONTENT_REJECTED" : "IMAGE_NOT_FOUND",
      {
        filename,
        type,
        subfolder,
        mimeType: result.mimeType,
        // The reason, structured, so a caller does not have to parse the sentence.
        // The reason rides along on BOTH kinds — a caller should not have to parse a
        // sentence to learn the server sent an error envelope rather than nothing at all.
        ...(jsonRefusal ? { rejectedBecause: jsonRefusal.reason } : {}),
      },
    );
  }

  return { ...result, filename };
}

/**
 * Byte ceiling for the JSON validation (#1373).
 *
 * A workflow is tens to hundreds of kilobytes; ComfyUI's own saves are well under a
 * megabyte. Parsing is the acceptance test, and parsing means decoding the whole payload
 * into a string and building an object graph from it — so an enormous body would be paid
 * for twice in memory before anything could reject it. 32 MB is far above any real
 * workflow and far below a problem.
 *
 * Above the ceiling the answer is REFUSE, not accept-unchecked: a `.json` that large is
 * not the workflow attachment this path exists to save, and accepting it unverified would
 * hand back exactly the unvalidated payload the surrounding guard is for.
 */
const MAX_JSON_ATTACHMENT_BYTES = 32 * 1024 * 1024;

/** Why a `.json` payload is not savable, and which of the two remedies applies. */
interface JsonRefusal {
  kind: "missing" | "content";
  reason: string;
}

/**
 * Why a `.json` payload is not savable, or null when it is (#1373).
 *
 * Returns a REASON rather than a boolean so the refusal can say what was actually wrong.
 * Collapsing "40 MB" and "this is an error envelope" into the generic "the file may not
 * exist in the ComfyUI input directory" sends the caller to check a filename that is
 * perfectly correct — which is the same wrong-cause failure this whole issue is about.
 *
 * WHAT COUNTS AS AN ERROR ENVELOPE (codex). A top-level `error` key alone was calibrated
 * wrong in both directions: it missed ComfyUI's other shapes (`node_errors`, `detail`) and
 * it rejected a legitimate workflow that happens to carry a top-level `error` field. The
 * test is now "carries an error-ish key AND carries none of the markers a workflow always
 * has" — so an error body is caught whatever it is called, and a real workflow is kept even
 * if it has an `error` extension of its own.
 */
function jsonAttachmentRefusal(base64: string): JsonRefusal | null {
  // WHY THE KIND EXISTS (codex round 3). "Nothing was saved" is one outcome with two
  // different remedies, and the remedy is the whole value of the answer:
  //
  //   missing — the server says it has no such file (an error envelope, or nothing at
  //             all). CHECK THE FILENAME. This is what IMAGE_NOT_FOUND means and what
  //             #385 added it for.
  //   content — a body arrived and it is not the attachment: an HTML login page from a
  //             proxy, a truncated stream, something over the ceiling. Checking the
  //             filename is useless here; the name was right and the payload was wrong.
  //
  // Deciding this on emptiness alone got the error-envelope case backwards: a `/view`
  // answering `{"error":"not found"}` for a file that is genuinely absent is the server
  // TELLING us it is absent, and routing that to "the payload was unusable" sends the
  // caller to inspect content instead of the name.
  if (base64.length === 0) return { kind: "missing", reason: "an empty response" };
  // Decoded size from the base64 LENGTH, minus padding, so the ceiling costs nothing to
  // enforce and does not overestimate a padded payload by a byte or two at the boundary.
  const padding = base64.endsWith("==") ? 2 : base64.endsWith("=") ? 1 : 0;
  const approxBytes = Math.floor((base64.length * 3) / 4) - padding;
  if (approxBytes > MAX_JSON_ATTACHMENT_BYTES) {
    return {
      kind: "content",
      reason:
        `a ${(approxBytes / 1024 ** 2).toFixed(1)} MB JSON body, over the ` +
        `${MAX_JSON_ATTACHMENT_BYTES / 1024 ** 2} MB ceiling for a workflow attachment — ` +
        `parsing it to check it would cost that much again in memory, so it was refused unread`,
    };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(Buffer.from(base64, "base64").toString("utf8"));
  } catch {
    return { kind: "content", reason: "a body that is not valid JSON" };
  }
  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
    const rec = parsed as Record<string, unknown>;
    const errorish = ["error", "node_errors", "detail"].filter((k) => k in rec);
    const workflowMarkers = ["nodes", "links", "last_node_id", "extra", "prompt", "workflow"];
    const looksLikeAWorkflow = workflowMarkers.some((k) => k in rec);
    if (errorish.length > 0 && !looksLikeAWorkflow) {
      return {
        // MISSING, not content. The server answered the request by saying it could not
        // serve it; the actionable fact is the name, not the bytes.
        kind: "missing",
        reason:
          `a JSON ERROR body (it carries "${errorish[0]}" and none of the keys a workflow has), ` +
          `not the attachment you asked for — saving it would write a failure to disk under ` +
          `the name of the thing that failed`,
      };
    }
  }
  return null;
}

/**
 * Upload a local image to ComfyUI via HTTP multipart POST.
 * Falls back to HTTP when COMFYUI_PATH is not available (remote ComfyUI).
 */
export async function uploadImageAuto(
  sourcePath: string,
  filename?: string,
): Promise<{ filename: string }> {
  const resolvedFilename = filename ?? basename(sourcePath);
  const ext = extname(resolvedFilename).toLowerCase();
  if (!(ext in IMAGE_MIME)) {
    throw new ValidationError(
      `Unsupported image format "${ext}". Supported: ${Object.keys(IMAGE_MIME).join(", ")}`,
    );
  }
  const data = await nodeReadFile(sourcePath);
  const mimeType = IMAGE_MIME[ext] ?? "application/octet-stream";
  logger.info("Uploading image to ComfyUI via HTTP", { sourcePath, resolvedFilename });
  const result = await uploadImageHttp(resolvedFilename, data, mimeType);
  return { filename: result.name };
}

// ---------------------------------------------------------------------------
// Video / audio upload — mirrors upload_image. ComfyUI's /upload/image endpoint
// (and the input/ directory) accept arbitrary media, which video/audio loader
// nodes (e.g. VHS_LoadVideo, LoadAudio) then read by filename.
// ---------------------------------------------------------------------------

const IMAGE_MIME: Record<string, string> = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".bmp": "image/bmp",
  ".gif": "image/gif",
  ".tiff": "image/tiff",
  ".tif": "image/tiff",
};

const VIDEO_MIME: Record<string, string> = {
  ".mp4": "video/mp4",
  ".mov": "video/quicktime",
  ".webm": "video/webm",
  ".avi": "video/x-msvideo",
  ".mkv": "video/x-matroska",
  ".m4v": "video/x-m4v",
};

const AUDIO_MIME: Record<string, string> = {
  ".wav": "audio/wav",
  ".mp3": "audio/mpeg",
  ".flac": "audio/flac",
  ".ogg": "audio/ogg",
  ".m4a": "audio/mp4",
  ".aac": "audio/aac",
};

function resolveMediaMime(
  filename: string,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): string {
  const ext = extname(filename).toLowerCase();
  const mime = mimeMap[ext];
  if (!mime) {
    throw new ValidationError(
      `Unsupported ${kind} format "${ext}". Supported: ${Object.keys(mimeMap).join(", ")}`,
    );
  }
  return mime;
}

/** HTTP multipart upload of a media file to ComfyUI's input/ (works remotely). */
async function uploadMediaHttp(
  sourcePath: string,
  filename: string | undefined,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): Promise<{ filename: string }> {
  const resolvedFilename = filename ?? basename(sourcePath);
  const mimeType = resolveMediaMime(resolvedFilename, mimeMap, kind);
  const data = await nodeReadFile(sourcePath);
  logger.info(`Uploading ${kind} to ComfyUI via HTTP`, { sourcePath, resolvedFilename });
  const result = await uploadImageHttp(resolvedFilename, data, mimeType);
  return { filename: result.name };
}

/** Local filesystem copy of a media file into ComfyUI's input/ (needs COMFYUI_PATH). */
async function uploadMediaLocal(
  sourcePath: string,
  filename: string | undefined,
  mimeMap: Record<string, string>,
  kind: "video" | "audio",
): Promise<{ filename: string; path: string }> {
  const inputDir = await getInputDir();
  const resolvedFilename = assertSafeInputFilename(filename ?? basename(sourcePath));
  resolveMediaMime(resolvedFilename, mimeMap, kind);
  const targetPath = join(inputDir, resolvedFilename);
  logger.info(`Uploading ${kind} to ComfyUI input`, { sourcePath, targetPath });
  try {
    await copyFile(sourcePath, targetPath);
  } catch (err) {
    throw new ValidationError(
      `Failed to copy ${kind}: ${err instanceof Error ? err.message : err}`,
    );
  }
  return { filename: resolvedFilename, path: targetPath };
}

export const uploadVideoAuto = (sourcePath: string, filename?: string) =>
  uploadMediaHttp(sourcePath, filename, VIDEO_MIME, "video");
export const uploadVideoLocal = (sourcePath: string, filename?: string) =>
  uploadMediaLocal(sourcePath, filename, VIDEO_MIME, "video");
export const uploadAudioAuto = (sourcePath: string, filename?: string) =>
  uploadMediaHttp(sourcePath, filename, AUDIO_MIME, "audio");
export const uploadAudioLocal = (sourcePath: string, filename?: string) =>
  uploadMediaLocal(sourcePath, filename, AUDIO_MIME, "audio");

// ---------------------------------------------------------------------------
// upload_image (action:"stage") — pipe one pipeline stage's OUTPUT into the next stage's
// loader (LoadImage / VHS_LoadVideo / LoadAudio) the CORRECT way: fetch the bytes
// from the ComfyUI server (/view) and re-register them as an INPUT via the same
// /upload/image endpoint the upload_* tools use. Because both legs go through the
// server API, this works even when ComfyUI was launched with a CUSTOM
// --input-directory / --output-directory — unlike copying or guessing a
// filesystem input/ path, which the server then rejects ("Invalid image file").
// ---------------------------------------------------------------------------

export type MediaKind = "image" | "video" | "audio";

const MIME_BY_KIND: Record<MediaKind, Record<string, string>> = {
  image: IMAGE_MIME,
  video: VIDEO_MIME,
  audio: AUDIO_MIME,
};

/** Infer image/video/audio from a filename's extension. */
export function inferMediaKind(filename: string): MediaKind {
  const ext = extname(filename).toLowerCase();
  if (ext in IMAGE_MIME) return "image";
  if (ext in VIDEO_MIME) return "video";
  if (ext in AUDIO_MIME) return "audio";
  throw new ValidationError(
    `Cannot infer media kind from extension "${ext}". ` +
      `Pass an explicit kind ("image" | "video" | "audio").`,
  );
}

/** Resolve the upload MIME type for a filename within a given media kind. */
function mimeForKind(filename: string, kind: MediaKind): string {
  const ext = extname(filename).toLowerCase();
  const mime = MIME_BY_KIND[kind][ext];
  if (!mime) {
    throw new ValidationError(
      `Extension "${ext}" is not a supported ${kind} format. ` +
        `Supported: ${Object.keys(MIME_BY_KIND[kind]).join(", ")}`,
    );
  }
  return mime;
}

export interface StageOutputAsInputArgs {
  /** Filename of the existing output/temp asset (from get_history / get_image (action:"list_outputs")). */
  filename: string;
  /** Subfolder the asset lives in, if any. */
  subfolder?: string;
  /** Source directory the asset currently lives in. "output" (default) or "temp" (previews). */
  type?: "output" | "temp";
  /** Force the media kind instead of inferring from the extension. */
  kind?: MediaKind;
  /** Override the filename it is registered under in the input/ directory. */
  asFilename?: string;
}

export interface StagedInput {
  /** Filename to drop into the loader's image/video/audio widget. */
  filename: string;
  /** Subfolder ComfyUI stored it under (usually ""). */
  subfolder: string;
  /** ComfyUI directory it now lives in (always "input"). */
  type: string;
  /** Detected/forced media kind. */
  kind: MediaKind;
}

/**
 * Stage an EXISTING ComfyUI output (or temp preview) as an INPUT, ready to feed
 * into the next stage's LoadImage / VHS_LoadVideo / LoadAudio loader.
 *
 * Fetches the bytes from the server via /view (the same path get_image uses) and
 * re-registers them as an input via /upload/image (the same path upload_image /
 * upload_image (action:"video") / upload_image (action:"audio") use). Goes entirely through the server API, so it
 * is correct even when ComfyUI runs with a custom input/output directory.
 */
export async function stageOutputAsInput(
  args: StageOutputAsInputArgs,
): Promise<StagedInput> {
  const sourceType = args.type ?? "output";
  const kind = args.kind ?? inferMediaKind(args.filename);
  const targetName = args.asFilename ?? basename(args.filename);
  const mimeType = mimeForKind(targetName, kind);

  // Fetch the existing asset's bytes via the same /view mechanism the asset
  // tools use (fetchImage handles cloud vs local). Despite the name, /view
  // returns raw bytes for any media type, not just images.
  const sourceSubfolder = args.subfolder ?? "";
  assertSafeViewRef(args.filename, sourceSubfolder);
  const { base64 } = await fetchImage(
    args.filename,
    sourceType,
    sourceSubfolder,
  );
  const data = Buffer.from(base64, "base64");

  logger.info("Staging ComfyUI output as input via server API", {
    source: args.filename,
    sourceType,
    kind,
    targetName,
  });

  const result = await uploadImageHttp(targetName, data, mimeType);
  return {
    filename: result.name,
    subfolder: result.subfolder,
    type: result.type,
    kind,
  };
}
